export const REQUIRED_AIRTABLE_RECONCILIATION_CHECK_KEYS = [
  'rejected_records',
  'clients_mapped',
  'projects_mapped',
  'salespeople_mapped',
  'leads_mapped',
  'qualifications_mapped',
  'scores_mapped',
  'messages_mapped',
  'followups_mapped',
  'appointments_mapped',
  'events_mapped',
  'contact_phone_uniqueness',
  'lead_contact_links',
  'lead_status_distribution',
  'active_leads_count',
  'stop_follow_up_count',
  'opt_out_count',
  'pending_followups_count',
  'open_booked_appointments_count',
  'message_provider_id_uniqueness',
] as const;
