export default {
  id: "real-estate",
  lang: "en",
  title: "Kadensio for Real Estate | WhatsApp leads scored out of 100",
  description:
    "Nine fixed questions on WhatsApp, in Arabic or English. Fixed arithmetic scoring, broker routing, and the viewing written into Google Calendar.",
  nav: [
    { label: "Mechanics", href: "#mechanics" },
    { label: "Scoring", href: "#scoring" },
    { label: "Dashboard", href: "#dashboard" },
    { label: "Questions", href: "#faq" },
  ],
  cta: { label: "Book a demo", subject: "Kadensio for Real Estate: demo" },
  hero: {
    eyebrow: "For real estate brokerages",
    h1: "Every WhatsApp lead scored out of 100 before a broker sees it.",
    lead:
      "Nine fixed questions. Arithmetic scoring. The viewing lands in the broker's Google Calendar.",
    proof: ["Official WhatsApp API", "No AI-generated replies", "Audit log per lead"],
  },
  mechanics: {
    id: "mechanics",
    eyebrow: "Mechanics",
    h2: "From first message to booked viewing in six steps.",
    lead: "Fixed script, official WhatsApp Business Platform. The fastest measured run took 30 seconds, from cold first message to booked appointment.",
    steps: [
      ["Inbound", "A WhatsApp number on a listing or a QR code on a hoarding. Website forms and Facebook lead ads feed the same flow."],
      ["Language", "The buyer picks Arabic or English before anything else. The engine never guesses from the phone number."],
      ["Nine questions", "Your wording, your order. Answers are recorded as the buyer gives them."],
      ["Score", "Ten weighted factors, capped at 100. The same answers always give the same number."],
      ["Route and book", "The lead goes to the salesperson who covers the project and speaks the language. A viewing slot is offered and written to Google Calendar."],
      ["Take over", "A salesperson takes the conversation in one tap, and hands it back when done."],
    ],
    questionsHeading: "The nine questions it ships with",
    questionsLead: "A starting point. Reword, reorder, drop or add. Scoring and routing stay the same fixed arithmetic whatever you ask.",
    questions: [
      "Permission", "Location", "Unit type",
      "Budget", "Payment plan", "Down payment",
      "Timeline", "Purpose", "Site visit interest",
    ],
  },
  scoring: {
    id: "scoring",
    eyebrow: "Scoring",
    h2: "A score a sales manager can check.",
    lead: "Every qualified lead gets 0 to 100. Ten factors, each worth fixed points, each with a written reason. Model real_estate_v1.",
    bands: [
      ["Hot", "75 or more"],
      ["Warm", "45 to 74"],
      ["Cold", "Below 45"],
    ],
    factorsCaption: "The ten factors and their points",
    factorsHead: ["Factor", "Points", "How it scores"],
    factors: [
      ["Baseline", "10", "Every scored lead starts here."],
      ["Budget", "8 to 25", "By the top of the declared budget. 10 million or more: 25. 5 million: 20. 3 million: 14. Any budget: 8."],
      ["Timeline", "2 to 20", "As soon as possible: 20. Within three months: 16. Within six months: 10. Just exploring: 2."],
      ["Site visit", "0 or 20", "Wanting to see the unit is the strongest buying signal in the model."],
      ["Payment plan", "6 to 12", "Cash: 12. Flexible: 8. Installments: 6."],
      ["Down payment", "0 to 12", "Against the bottom of the budget. 20% or more: 12. 10% or more: 8. Any amount: 4."],
      ["Purpose", "0 to 8", "Investment, or investment and residence: 8. Primary residence: 5."],
      ["Unit type", "3 to 6", "Villa, townhouse or commercial: 6. Apartment: 4. Any other type: 3."],
      ["Location", "0 or 5", "A named location, so routing can find the salesperson who covers it."],
      ["Qualification complete", "0 or 5", "The buyer answered every question."],
    ],
    capNote: "The maximums add up to 123 and the score is capped at 100, so a lead can reach the top without a perfect answer on each factor. Missing answers score zero, and the dashboard lists them.",
    exampleHeading: "A worked example",
    exampleLead: "An apartment in New Cairo, budget 3 to 5 million, installments with 500,000 down, buying within three months, for their own home, wants a site visit.",
    exampleCaption: "One lead, scored",
    exampleHead: ["Factor", "Points", "Answer"],
    example: [
      ["Baseline", 10, "Any scored lead"],
      ["Budget", 20, "Up to 5,000,000"],
      ["Timeline", 16, "Within three months"],
      ["Site visit", 20, "Yes"],
      ["Payment plan", 6, "Installments"],
      ["Down payment", 8, "500,000 against 3,000,000 (17%)"],
      ["Purpose", 5, "Primary residence"],
      ["Unit type", 4, "Apartment"],
      ["Location", 5, "New Cairo"],
      ["Qualification complete", 5, "All nine answered"],
    ],
    exampleScore: 99,
    exampleBand: "Hot",
    exampleClose: "Give the engine the same nine answers next month and it returns 99 again. Each score is stored with the model version and a fingerprint of the answers behind it.",
    fullLink: { label: "The full scoring model", href: "https://kadensio.com/lead-scoring.html" },
  },
  dashboard: {
    id: "dashboard",
    eyebrow: "Dashboard",
    h2: "The hottest lead first, with the whole conversation attached.",
    lead: "The first call starts where the qualification ended.",
    image: {
      base: "product-queue",
      alt: "The Kadensio lead queue: eight leads ranked by urgency, each with what the buyer wants, a temperature and how long they have been waiting. Sample data.",
      caption: "The lead queue, as your team sees it. Sample data.",
    },
    rows: [
      ["Hot leads first", "The queue is sorted by score. Every score opens to the ten factors behind it."],
      ["The whole conversation", "Every answer in the buyer's own words, before anyone picks up the phone. Reply from the same screen."],
      ["Why this salesperson", "Routing matches project, unit type, location and language, weighs current load, and records every candidate it considered."],
      ["Take over in one tap", "Taking over stops the engine replying to that buyer until someone hands the conversation back."],
      ["Nothing waits unnoticed", "A reminder at 15 minutes, a manager alert at 30, and one list of every lead still waiting for a reply."],
      ["Manager overview", "Speed to acknowledge, new and qualified leads, and where leads come from, by week or by month."],
    ],
  },
  faq: {
    id: "faq",
    eyebrow: "Questions",
    h2: "What brokers ask first.",
    items: [
      ["Is this a chatbot?", "No. A chatbot writes its own replies. Kadensio sends the replies you approved, in the order you set, and scores the answers with fixed arithmetic. It contains no generative model, so it cannot make up a price, a payment plan or a unit."],
      ["What if an answer does not fit the question?", "It asks once more. If the second answer still does not fit, it saves the buyer's own words as a note for your salesperson and moves on."],
      ["Can a salesperson step in?", "At any point. Taking over stops the engine replying to that buyer until someone hands the conversation back."],
      ["What happens when a buyer says stop?", "The engine opts them out on the spot, stops messaging them and marks the lead as not interested."],
      ["Does it work with the number we already use?", "It runs on the Meta WhatsApp Business Platform, so the number is registered there. If your buyers know a number on the ordinary WhatsApp Business app today, moving it is the first thing we go through together."],
      ["Which languages does it speak?", "Arabic and English ship, both tested against the production API. Any other language your buyers use is written and loaded during setup."],
    ],
  },
  closing: {
    id: "demo",
    eyebrow: "Try it",
    h2: "Test it from your own phone.",
    lead: "This is the live production system. Message it the way a buyer would: it asks for Arabic or English, runs the nine questions, scores you and offers a viewing slot. It books nothing on your behalf.",
    secondary: { label: "Try it on WhatsApp", href: "https://wa.me/201041445227?text=Hi" },
  },
  footer: {
    meta: "WhatsApp lead qualification for real estate brokerages.",
    sibling: { label: "Also built for hospitality", id: "hospitality" },
  },
};
